version: '3.7'

services:      
  mariadb:
      container_name: ${CONTAINER_NAME:-dev-mariadb}
      image: mariadb
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
        - MYSQL_DATABASE=${MYSQL_ROOT_DATABASE:-db}

      networks:
        - dev-network
      ports:
        - '3306:3306'
      volumes:
      - ./data/db:/data/db

  # microservice:
  #   build:
  #     context: ./
  #   ports:
  #     - '3333:3333'
  #   depends_on:
  #     - mariadb
  #   networks:
  #     - dev-network

# DEV Network
networks:
  dev-network:
    name: dev-network
    driver: bridge
